### ISSUE TITLE
Add chat filter 

### ISSUE THREAD

**Issue by residal** [Warzone/TGM#605]
**Describe the feature you'd like**
A chat filter that prevents players from committing certain chat offenses.

**Usefulness of the feature**
Makes staff members jobs easier as well as improving the experience of everybody in the community.

**Additional info**
By adding the chat filter, players will not be able to commit certain chat offenses. 
Examples of where the chat filter would take effect:
- Player attempts to send over 3 identical messages
- Player uses capital letters excessively
- Player uses a racial slur

Player is told why the message wasn't sent and is directed to the rules.

**Comment by Owehttamy** [comment]
+1 but it would be even better if, for example someone tried saying a racial slur. Instead of just preventing the message from being sent. either they're given a mute, or the message looks like it's sent to the offender but not to anybody else. This would be better because it'd prevent players from trying to get around the chat filter by adding numbers into slurs or other nonsense.

**Comment by BennyDoesStuff** [comment]
I’m a bit hesitant on this, do you guys think this is something that should be implemented in TGM? If so, how advanced should it be? It seems a bit questionable since the original goal of the plugin was for team management, but then having ranks and everything already voids that argument.

**Comment by AtditC** [comment]
-1 for a chat filter

**Comment by BennyDoesStuff** [comment]
I'm going to close this issue for now, I feel like a chat filter should be something not implemented in the TGM plugin itself.
