### ISSUE TITLE
Unnecessary deaths being given to players

### ISSUE THREAD

**Issue by residal** [Warzone/TGM#772]
**Describe the bug**
- Switching teams shortly after killing a player, gives you a death.
- Switching teams while in the respawn screen gives you a death.
- Switching teams after respawning gives you a death.

When this happens, it typically shows **[Player] died.** in chat.

**Client version**
1.8.9

**To Reproduce**
Steps to reproduce the bug:
1. Join a match
2. Switch teams after killing a player, respawning, or while you're in the respawn screen.

**Expected behavior**
The expected behavior would be when you do any of the things listed above, you do not receive an unnecessary death.

**Additional context**
I believe this issue stems from a newly implemented system designed to give deaths to players that log out during combat.

**Comment by jorgeberrex** [comment]
> Switching teams shortly after killing a player, gives you a death.

This is normal behavior. When you enter combat and get hit by the other player, you get a combat cooldown that does not reset after the player has been killed. 

> Switching teams while in the respawn screen gives you a death.

Could not replicate this since switching teams while in the respawn screen is not possible and using `/team force` does not kill the player, only drop their items.
